### PR TITLE
Added ability to modify pun frequency from zulip.

### PR DESCRIPTION
**Pull request by anneal**
Added ability to modify pun frequency from zulip using "more" or "less" commands.

Added aliases for "go away".

### CODE REVIEW

**Comment by maiamcc** [comment]
Awesome! A few small changes:
- could you update the help message to reflect more/less pun?
- the adjustment for more/less pun should maybe be smaller? Maybe .1?
- more/less pun should print "[silly message](Pun chance = 0.1)"
  Yay! :+1:

**Comment by maiamcc** [comment]
Oh shoot wait! I just realized that your commands will adjust pun chance for all of punbot, not just for the topic in question. Can you make it topic-specific?

**Comment by anneal** [comment]
Ok. I updated the file to meet all those ideas. 

HOWEVER, I cannot test this in Zulip so I ran tests locally on each of the isolated functions. I can test it thoroughly in a PM with pun bot after pulling. Or is there some way that I can test it in Zulip?

**Comment by maiamcc** [comment]
Yes you can! I'll PM with instructions.

**Pull request merged**
